int _putchar(char c);
void reset_to_98(int *n);
void swao_int(int *a, int *b);
int _strln(char *s);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void outs2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
int _atoi(char *s);
